version: '3.3'

services:
  product_adm_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: product_adm
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - product_adm_database:/var/lib/mysql

  client_adm_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: client_adm
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3307:3306'
    expose:
      - '3307'
    volumes:
      - client_adm_database:/var/lib/mysql

  checkout_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: checkout
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3308:3306'
    expose:
      - '3308'
    volumes:
      - checkout_database:/var/lib/mysql

  store_catalog_db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: store_catalog
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3309:3306'
    expose:
      - '3309'
    volumes:
      - store_catalog_database:/var/lib/mysql

volumes:
  product_adm_database:
  client_adm_database:
  checkout_database:
  store_catalog_database:
